### ISSUE TITLE
audio watermark question

### ISSUE THREAD

**Issue by HamidLaktarash** [swesterfeld/audiowmark#14] opened 2022-04-13 06:25 UTC
Hi. it's me again. I have a question for you. I'd be grateful if you help me.
I gonna implement program that embed and hide 12 digits decimal number into .wav file audio signal and it's don't affect to file sound human hear, then after while I want extract same 12 digits decimal number from those files. I know somethings about NAudio .net , Fast Fourier Transform.
I have below algorithm idea but I can't implement it.
Through Using Fourier Transform, I change main .wav file to frequency domain then make a signal in frequency domain form 12 digits number in less than 20 hz ( because it`s not hear by human ) and then merge two signal to one signal in frequency domain and finally operate Inverse Fourier Transform to back to time domain. in other hand I should process some file and extract numbers

**Comment by swesterfeld** [comment] 2022-05-16 13:18
This is not really a bug or feature request, so I'm closing the issue. But here are a few thoughts:

- If you just want to watermark audio signals with your payload without making it audible, you could use `audiowmark` to do it.

- Depending on your requirements, implementing watermarking yourself could be a lot of work. What `audiowmark` uses is called the patchwork algorithm.

- If you just embed the information in the inaudible part of the spectrum (<20 Hz) the problem is that modern codecs remove everything that is inaudible, so for instance the information could be gone after mp3 encoding.

**Closed by swesterfeld** 2022-05-16 13:18 UTC
